### ISSUE TITLE
Module name different with repository name

### ISSUE THREAD

**Issue by Databingo** [CNZeroY/googleBard#1]
When import as  "github.com/CNZeroY/google-bard", get error report:

go: finding module for package github.com/CNZeroY/google-bard
go: found github.com/CNZeroY/google-bard in github.com/CNZeroY/google-bard v0.0.0-20230404092539-731d5a86edcd
go: main imports
        github.com/CNZeroY/google-bard: github.com/CNZeroY/google-bard@v0.0.0-20230404092539-731d5a86edcd: parsing go.mod:
        module declares its path as: googleBard
                but was required as: github.com/CNZeroY/google-bard

**Comment by zeroy1024** [comment]
Sry,I didn't consider using package references at the beginning, now it works `go get github.com/CNZeroY/googleBard`
